- name: be sure sensu apt repository key is deployed
  apt_key:
    url: http://sensu.global.ssl.fastly.net/apt/pubkey.gpg

- name: be sure sensu apt repository is deployed
  apt_repository:
    repo: deb http://sensu.global.ssl.fastly.net/apt sensu main
    update_cache: yes

- name: be sure sensu is installed
  apt:
    name: sensu
    state: latest
